# person={
#  'name':'jack',
#  'age':20,
#  'gender':'male',
#  4:'organisation'}

# result = person['age'] 
# x = person.get("gender")
# print(person[4])
# print(x)
# print(result)

# dict={
#     "brand":"ford",
#     "mode":"mustang",
#     "year":1964
# }
# for x in dict:
#   print(x)


# for x in dict:
#     print(dict[x])


# for x in dict.values():
#   print(x)


# for x, y in dict.items():
#   print(x, y)



# thisdict = {
#   "brand": "Ford",
#   "model": "Mustang",
#   "year": 1964
# }
# mydict = thisdict.copy()
# print(mydict)


# thisdict = {
#   "brand": "Ford",
#   "model": "Mustang",
#   "year": 1964
# }
# mydict = dict(thisdict)
# print(mydict)













